# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/671fcc5b-4274-4233-9639-52164b48eff8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/01C0-8687";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/HDD-2" =
    { device = "/dev/disk/by-uuid/9dc10468-0846-404f-95f3-f958c8a0b3c8";
      fsType = "btrfs";
    };

  fileSystems."/mnt/SSD-1" =
    { device = "/dev/disk/by-uuid/d184fe66-ca48-4a26-b4c8-c06f29b12515";
      fsType = "btrfs";
    };

  fileSystems."/mnt/HDD-1" =
    { device = "/dev/disk/by-uuid/3a063f96-68ab-4888-a424-7ca920880100";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
